// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:cineswipe/data/models/actor_model.dart';
import 'package:cineswipe/data/models/movie_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActorAdapter());
    registerAdapter(MovieAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActorAdapter());
    registerAdapter(MovieAdapter());
  }
}
